// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/verbiscms/verbis/api/domain"
)

// valuer is an autogenerated mock type for the valuer type
type valuer struct {
	mock.Mock
}

// Execute provides a mock function with given fields: field
func (_m *valuer) Execute(field domain.FieldValue) (interface{}, error) {
	ret := _m.Called(field)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(domain.FieldValue) interface{}); ok {
		r0 = rf(field)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.FieldValue) error); ok {
		r1 = rf(field)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
