// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

// NotFound provides a mock function with given fields: g
func (_m *ErrorHandler) NotFound(g *gin.Context) {
	_m.Called(g)
}
