// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// headerWriter is an autogenerated mock type for the headerWriter type
type headerWriter struct {
	mock.Mock
}

// Cache provides a mock function with given fields: g
func (_m *headerWriter) Cache(g *gin.Context) {
	_m.Called(g)
}
