// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: postID, catID
func (_m *Repository) Create(postID int, catID int) error {
	ret := _m.Called(postID, catID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(postID, catID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: postID
func (_m *Repository) Delete(postID int) error {
	ret := _m.Called(postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Update provides a mock function with given fields: postID, catID
func (_m *Repository) Update(postID int, catID int) error {
	ret := _m.Called(postID, catID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, int) error); ok {
		r0 = rf(postID, catID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
