// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: postID
func (_m *Repository) Delete(postID int) error {
	ret := _m.Called(postID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: postID
func (_m *Repository) Exists(postID int) bool {
	ret := _m.Called(postID)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int) bool); ok {
		r0 = rf(postID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Insert provides a mock function with given fields: postID, catID
func (_m *Repository) Insert(postID int, catID *int) error {
	ret := _m.Called(postID, catID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, *int) error); ok {
		r0 = rf(postID, catID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
