// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// RedirectHandler is an autogenerated mock type for the RedirectHandler type
type RedirectHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: g
func (_m *RedirectHandler) Create(g *gin.Context) {
	_m.Called(g)
}

// Delete provides a mock function with given fields: g
func (_m *RedirectHandler) Delete(g *gin.Context) {
	_m.Called(g)
}

// Get provides a mock function with given fields: g
func (_m *RedirectHandler) Get(g *gin.Context) {
	_m.Called(g)
}

// GetById provides a mock function with given fields: g
func (_m *RedirectHandler) GetById(g *gin.Context) {
	_m.Called(g)
}

// Update provides a mock function with given fields: g
func (_m *RedirectHandler) Update(g *gin.Context) {
	_m.Called(g)
}
