// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserHandler is an autogenerated mock type for the UserHandler type
type UserHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: g
func (_m *UserHandler) Create(g *gin.Context) {
	_m.Called(g)
}

// Delete provides a mock function with given fields: g
func (_m *UserHandler) Delete(g *gin.Context) {
	_m.Called(g)
}

// Get provides a mock function with given fields: g
func (_m *UserHandler) Get(g *gin.Context) {
	_m.Called(g)
}

// GetById provides a mock function with given fields: g
func (_m *UserHandler) GetById(g *gin.Context) {
	_m.Called(g)
}

// GetRoles provides a mock function with given fields: g
func (_m *UserHandler) GetRoles(g *gin.Context) {
	_m.Called(g)
}

// ResetPassword provides a mock function with given fields: g
func (_m *UserHandler) ResetPassword(g *gin.Context) {
	_m.Called(g)
}

// Update provides a mock function with given fields: g
func (_m *UserHandler) Update(g *gin.Context) {
	_m.Called(g)
}
