// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	environment "github.com/ainsleyclark/verbis/api/environment"

	mock "github.com/stretchr/testify/mock"

	stow "github.com/graymeta/stow"
)

// providerFunc is an autogenerated mock type for the providerFunc type
type providerFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: env, storagePath
func (_m *providerFunc) Execute(env *environment.Env, storagePath string) (stow.Location, error) {
	ret := _m.Called(env, storagePath)

	var r0 stow.Location
	if rf, ok := ret.Get(0).(func(*environment.Env, string) stow.Location); ok {
		r0 = rf(env, storagePath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(stow.Location)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*environment.Env, string) error); ok {
		r1 = rf(env, storagePath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
