// Copyright 2020 The Verbis Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package updates

// Code generated by go generate; DO NOT EDIT.

func init() {
	// Version: v0.0.1
	UpdateRegistry.Add(Update{
		Version:   "v0.0.1",
		Migration: "SELECT * FROM posts",
		Callback:  nil,
	})
	// Version: v0.0.2
	UpdateRegistry.Add(Update{
		Version:   "v0.0.2",
		Migration: "SELECT * FROM post_fields",
		Callback:  nil,
	})
}
