// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	config "github.com/ainsleyclark/verbis/api/config"

	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// ErrorHandler is an autogenerated mock type for the ErrorHandler type
type ErrorHandler struct {
	mock.Mock
}

// NotFound provides a mock function with given fields: g, _a1
func (_m *ErrorHandler) NotFound(g *gin.Context, _a1 config.Configuration) {
	_m.Called(g, _a1)
}
