// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Assets provides a mock function with given fields: ctx
func (_m *Handler) Assets(ctx *gin.Context) {
	_m.Called(ctx)
}

// Screenshot provides a mock function with given fields: ctx
func (_m *Handler) Screenshot(ctx *gin.Context) {
	_m.Called(ctx)
}

// Serve provides a mock function with given fields: ctx
func (_m *Handler) Serve(ctx *gin.Context) {
	_m.Called(ctx)
}

// Uploads provides a mock function with given fields: ctx
func (_m *Handler) Uploads(ctx *gin.Context) {
	_m.Called(ctx)
}
