// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ExistsFunc is an autogenerated mock type for the ExistsFunc type
type ExistsFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: fileName
func (_m *ExistsFunc) Execute(fileName string) bool {
	ret := _m.Called(fileName)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(fileName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
