// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"

	mock "github.com/stretchr/testify/mock"

	multipart "mime/multipart"
)

// Library is an autogenerated mock type for the Library type
type Library struct {
	mock.Mock
}

// Delete provides a mock function with given fields: id
func (_m *Library) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Upload provides a mock function with given fields: file, userID
func (_m *Library) Upload(file *multipart.FileHeader, userID int) (domain.Media, error) {
	ret := _m.Called(file, userID)

	var r0 domain.Media
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, int) domain.Media); ok {
		r0 = rf(file, userID)
	} else {
		r0 = ret.Get(0).(domain.Media)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*multipart.FileHeader, int) error); ok {
		r1 = rf(file, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Validate provides a mock function with given fields: file
func (_m *Library) Validate(file *multipart.FileHeader) error {
	ret := _m.Called(file)

	var r0 error
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader) error); ok {
		r0 = rf(file)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
