// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	media "github.com/ainsleyclark/verbis/api/services/media"

	mock "github.com/stretchr/testify/mock"
)

// Resizer is an autogenerated mock type for the Resizer type
type Resizer struct {
	mock.Mock
}

// Resize provides a mock function with given fields: imager, dest, _a2, comp
func (_m *Resizer) Resize(imager media.Imager, dest string, _a2 domain.MediaSize, comp int) error {
	ret := _m.Called(imager, dest, _a2, comp)

	var r0 error
	if rf, ok := ret.Get(0).(func(media.Imager, string, domain.MediaSize, int) error); ok {
		r0 = rf(imager, dest, _a2, comp)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
