// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"

	mock "github.com/stretchr/testify/mock"
)

// Finder is an autogenerated mock type for the Finder type
type Finder struct {
	mock.Mock
}

// GetLayout provides a mock function with given fields: p, a, c, cacheable
func (_m *Finder) GetLayout(p domain.Post, a domain.User, c *domain.Category, cacheable bool) []domain.FieldGroup {
	ret := _m.Called(p, a, c, cacheable)

	var r0 []domain.FieldGroup
	if rf, ok := ret.Get(0).(func(domain.Post, domain.User, *domain.Category, bool) []domain.FieldGroup); ok {
		r0 = rf(p, a, c, cacheable)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FieldGroup)
		}
	}

	return r0
}
