// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	http "github.com/ainsleyclark/verbis/api/http"
	mock "github.com/stretchr/testify/mock"
)

// Parameterize is an autogenerated mock type for the Parameterize type
type Parameterize struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Parameterize) Get() http.Params {
	ret := _m.Called()

	var r0 http.Params
	if rf, ok := ret.Get(0).(func() http.Params); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(http.Params)
	}

	return r0
}
