// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	websocket "github.com/gorilla/websocket"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

// Reader provides a mock function with given fields: ws
func (_m *Connector) Reader(ws *websocket.Conn) {
	_m.Called(ws)
}

// Writer provides a mock function with given fields: ws
func (_m *Connector) Writer(ws *websocket.Conn) {
	_m.Called(ws)
}
