// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	bytes "bytes"

	domain "github.com/ainsleyclark/verbis/api/domain"
	image "github.com/ainsleyclark/verbis/api/services/media/image"

	mock "github.com/stretchr/testify/mock"
)

// Resizer is an autogenerated mock type for the Resizer type
type Resizer struct {
	mock.Mock
}

// Resize provides a mock function with given fields: imager, media
func (_m *Resizer) Resize(imager image.Imager, media domain.MediaSize) (*bytes.Reader, error) {
	ret := _m.Called(imager, media)

	var r0 *bytes.Reader
	if rf, ok := ret.Get(0).(func(image.Imager, domain.MediaSize) *bytes.Reader); ok {
		r0 = rf(imager, media)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Reader)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(image.Imager, domain.MediaSize) error); ok {
		r1 = rf(imager, media)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
