// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Layout provides a mock function with given fields: post
func (_m *Repository) Layout(post domain.PostDatum) domain.FieldGroups {
	ret := _m.Called(post)

	var r0 domain.FieldGroups
	if rf, ok := ret.Get(0).(func(domain.PostDatum) domain.FieldGroups); ok {
		r0 = rf(post)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.FieldGroups)
		}
	}

	return r0
}
