// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	bytes "bytes"
	image "image"

	mock "github.com/stretchr/testify/mock"
)

// Imager is an autogenerated mock type for the Imager type
type Imager struct {
	mock.Mock
}

// Decode provides a mock function with given fields:
func (_m *Imager) Decode() (image.Image, error) {
	ret := _m.Called()

	var r0 image.Image
	if rf, ok := ret.Get(0).(func() image.Image); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(image.Image)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Encode provides a mock function with given fields: _a0, comp
func (_m *Imager) Encode(_a0 image.Image, comp int) (*bytes.Buffer, error) {
	ret := _m.Called(_a0, comp)

	var r0 *bytes.Buffer
	if rf, ok := ret.Get(0).(func(image.Image, int) *bytes.Buffer); ok {
		r0 = rf(_a0, comp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bytes.Buffer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(image.Image, int) error); ok {
		r1 = rf(_a0, comp)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
