// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// ListBuckets provides a mock function with given fields:
func (_m *Provider) ListBuckets() (domain.Buckets, error) {
	ret := _m.Called()

	var r0 domain.Buckets
	if rf, ok := ret.Get(0).(func() domain.Buckets); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Buckets)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetBucket provides a mock function with given fields: id
func (_m *Provider) SetBucket(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetProvider provides a mock function with given fields: location
func (_m *Provider) SetProvider(location domain.StorageProvider) error {
	ret := _m.Called(location)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.StorageProvider) error); ok {
		r0 = rf(location)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
