// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	template "html/template"
)

// Func is an autogenerated mock type for the Func type
type Func struct {
	mock.Mock
}

// Execute provides a mock function with given fields: name, data
func (_m *Func) Execute(name string, data ...interface{}) (template.HTML, error) {
	var _ca []interface{}
	_ca = append(_ca, name)
	_ca = append(_ca, data...)
	ret := _m.Called(_ca...)

	var r0 template.HTML
	if rf, ok := ret.Get(0).(func(string, ...interface{}) template.HTML); ok {
		r0 = rf(name, data...)
	} else {
		r0 = ret.Get(0).(template.HTML)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, ...interface{}) error); ok {
		r1 = rf(name, data...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
