// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	store "github.com/eko/gocache/v2/store"
	mock "github.com/stretchr/testify/mock"
)

// provider is an autogenerated mock type for the provider type
type provider struct {
	mock.Mock
}

// Driver provides a mock function with given fields:
func (_m *provider) Driver() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Ping provides a mock function with given fields:
func (_m *provider) Ping() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Store provides a mock function with given fields:
func (_m *provider) Store() store.StoreInterface {
	ret := _m.Called()

	var r0 store.StoreInterface
	if rf, ok := ret.Get(0).(func() store.StoreInterface); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(store.StoreInterface)
		}
	}

	return r0
}

// Validate provides a mock function with given fields:
func (_m *provider) Validate() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
