// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	environment "github.com/verbiscms/verbis/api/environment"
)

// ProviderAdder is an autogenerated mock type for the providerAdder type
type ProviderAdder struct {
	mock.Mock
}

// Execute provides a mock function with given fields: env
func (_m *ProviderAdder) Execute(env *environment.Env) cache.provider {
	ret := _m.Called(env)

	var r0 cache.provider
	if rf, ok := ret.Get(0).(func(*environment.Env) cache.provider); ok {
		r0 = rf(env)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(cache.provider)
		}
	}

	return r0
}
