// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/verbiscms/verbis/api/domain"
)

// Provider is an autogenerated mock type for the Provider type
type Provider struct {
	mock.Mock
}

// Get provides a mock function with given fields: theme
func (_m *Provider) Get(theme string) (domain.ThemeConfig, error) {
	ret := _m.Called(theme)

	var r0 domain.ThemeConfig
	if rf, ok := ret.Get(0).(func(string) domain.ThemeConfig); ok {
		r0 = rf(theme)
	} else {
		r0 = ret.Get(0).(domain.ThemeConfig)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(theme)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
