// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Create provides a mock function with given fields: mediaId, _a1
func (_m *Repository) Create(mediaId int, _a1 domain.MediaSizes) (domain.MediaSizes, error) {
	ret := _m.Called(mediaId, _a1)

	var r0 domain.MediaSizes
	if rf, ok := ret.Get(0).(func(int, domain.MediaSizes) domain.MediaSizes); ok {
		r0 = rf(mediaId, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.MediaSizes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int, domain.MediaSizes) error); ok {
		r1 = rf(mediaId, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: mediaId
func (_m *Repository) Delete(mediaId int) error {
	ret := _m.Called(mediaId)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(mediaId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Find provides a mock function with given fields: mediaId
func (_m *Repository) Find(mediaId int) (domain.MediaSizes, error) {
	ret := _m.Called(mediaId)

	var r0 domain.MediaSizes
	if rf, ok := ret.Get(0).(func(int) domain.MediaSizes); ok {
		r0 = rf(mediaId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.MediaSizes)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(mediaId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
