// Copyright 2020 The Verbis Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Importer is an autogenerated mock type for the Importer type
type Importer struct {
	mock.Mock
}

// Import provides a mock function with given fields:
func (_m *Importer) Import() {
	_m.Called()
}
