// Copyright 2020 The Verbis Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// uploader is an autogenerated mock type for the uploader type
type uploader struct {
	mock.Mock
}

// Execute provides a mock function with given fields: file, url, err
func (_m *uploader) Execute(file *multipart.FileHeader, url string, err error) string {
	ret := _m.Called(file, url, err)

	var r0 string
	if rf, ok := ret.Get(0).(func(*multipart.FileHeader, string, error) string); ok {
		r0 = rf(file, url, err)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
