// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"

	mock "github.com/stretchr/testify/mock"
)

// test is an autogenerated mock type for the test type
type test struct {
	mock.Mock
}

// GetFieldGroups provides a mock function with given fields:
func (_m *test) GetFieldGroups() (*[]domain.FieldGroup, error) {
	ret := _m.Called()

	var r0 *[]domain.FieldGroup
	if rf, ok := ret.Get(0).(func() *[]domain.FieldGroup); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.FieldGroup)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
