// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Delete provides a mock function with given fields: formID
func (_m *Repository) Delete(formID int) error {
	ret := _m.Called(formID)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(formID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: formID, f
func (_m *Repository) Exists(formID int, f domain.FormField) bool {
	ret := _m.Called(formID, f)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, domain.FormField) bool); ok {
		r0 = rf(formID, f)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Find provides a mock function with given fields: formID
func (_m *Repository) Find(formID int) (domain.FormFields, error) {
	ret := _m.Called(formID)

	var r0 domain.FormFields
	if rf, ok := ret.Get(0).(func(int) domain.FormFields); ok {
		r0 = rf(formID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.FormFields)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(formID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Insert provides a mock function with given fields: formID, f
func (_m *Repository) Insert(formID int, f domain.FormField) error {
	ret := _m.Called(formID, f)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.FormField) error); ok {
		r0 = rf(formID, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
