// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	mail "github.com/ainsleyclark/go-mail"
	mock "github.com/stretchr/testify/mock"
)

// Dispatcher is an autogenerated mock type for the Dispatcher type
type Dispatcher struct {
	mock.Mock
}

// Dispatch provides a mock function with given fields: data, recipients, a
func (_m *Dispatcher) Dispatch(data interface{}, recipients []string, a mail.Attachments) error {
	ret := _m.Called(data, recipients, a)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}, []string, mail.Attachments) error); ok {
		r0 = rf(data, recipients, a)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
