// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	nav "github.com/verbiscms/verbis/api/verbis/nav"
)

// Getter is an autogenerated mock type for the Getter type
type Getter struct {
	mock.Mock
}

// Get provides a mock function with given fields: args
func (_m *Getter) Get(args nav.Args) (nav.Menu, error) {
	ret := _m.Called(args)

	var r0 nav.Menu
	if rf, ok := ret.Get(0).(func(nav.Args) nav.Menu); ok {
		r0 = rf(args)
	} else {
		r0 = ret.Get(0).(nav.Menu)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(nav.Args) error); ok {
		r1 = rf(args)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetFromOptions provides a mock function with given fields: opts
func (_m *Getter) GetFromOptions(opts nav.Options) (nav.Menu, error) {
	ret := _m.Called(opts)

	var r0 nav.Menu
	if rf, ok := ret.Get(0).(func(nav.Options) nav.Menu); ok {
		r0 = rf(opts)
	} else {
		r0 = ret.Get(0).(nav.Menu)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(nav.Options) error); ok {
		r1 = rf(opts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
