// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/verbiscms/verbis/api/domain"
)

// Installer is an autogenerated mock type for the Installer type
type Installer struct {
	mock.Mock
}

// Install provides a mock function with given fields: db
func (_m *Installer) Install(db domain.InstallVerbis) error {
	ret := _m.Called(db)

	var r0 error
	if rf, ok := ret.Get(0).(func(domain.InstallVerbis) error); ok {
		r0 = rf(db)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateInstall provides a mock function with given fields: step, install
func (_m *Installer) ValidateInstall(step int, install domain.InstallVerbis) error {
	ret := _m.Called(step, install)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.InstallVerbis) error); ok {
		r0 = rf(step, install)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
