// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// FieldsRepository is an autogenerated mock type for the FieldsRepository type
type FieldsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: f
func (_m *FieldsRepository) Create(f domain.PostField) (domain.PostField, error) {
	ret := _m.Called(f)

	var r0 domain.PostField
	if rf, ok := ret.Get(0).(func(domain.PostField) domain.PostField); ok {
		r0 = rf(f)
	} else {
		r0 = ret.Get(0).(domain.PostField)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.PostField) error); ok {
		r1 = rf(f)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByPost provides a mock function with given fields: postId
func (_m *FieldsRepository) GetByPost(postId int) ([]domain.PostField, error) {
	ret := _m.Called(postId)

	var r0 []domain.PostField
	if rf, ok := ret.Get(0).(func(int) []domain.PostField); ok {
		r0 = rf(postId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PostField)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(postId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetLayout provides a mock function with given fields: p, a, c
func (_m *FieldsRepository) GetLayout(p domain.Post, a domain.User, c *domain.Category) []domain.FieldGroup {
	ret := _m.Called(p, a, c)

	var r0 []domain.FieldGroup
	if rf, ok := ret.Get(0).(func(domain.Post, domain.User, *domain.Category) []domain.FieldGroup); ok {
		r0 = rf(p, a, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.FieldGroup)
		}
	}

	return r0
}

// UpdateCreate provides a mock function with given fields: postId, f
func (_m *FieldsRepository) UpdateCreate(postId int, f []domain.PostField) error {
	ret := _m.Called(postId, f)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, []domain.PostField) error); ok {
		r0 = rf(postId, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
