// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// FieldsRepository is an autogenerated mock type for the FieldsRepository type
type FieldsRepository struct {
	mock.Mock
}

// GetLayout provides a mock function with given fields: p, a, c
func (_m *FieldsRepository) GetLayout(p domain.Post, a domain.User, c *domain.Category) *[]domain.FieldGroup {
	ret := _m.Called(p, a, c)

	var r0 *[]domain.FieldGroup
	if rf, ok := ret.Get(0).(func(domain.Post, domain.User, *domain.Category) *[]domain.FieldGroup); ok {
		r0 = rf(p, a, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]domain.FieldGroup)
		}
	}

	return r0
}
