// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	http "github.com/ainsleyclark/verbis/api/http"

	mock "github.com/stretchr/testify/mock"
)

// PostsRepository is an autogenerated mock type for the PostsRepository type
type PostsRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: p
func (_m *PostsRepository) Create(p *domain.PostCreate) (domain.Post, error) {
	ret := _m.Called(p)

	var r0 domain.Post
	if rf, ok := ret.Get(0).(func(*domain.PostCreate) domain.Post); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.PostCreate) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *PostsRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: slug
func (_m *PostsRepository) Exists(slug string) bool {
	ret := _m.Called(slug)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Format provides a mock function with given fields: post
func (_m *PostsRepository) Format(post domain.Post) (domain.PostData, error) {
	ret := _m.Called(post)

	var r0 domain.PostData
	if rf, ok := ret.Get(0).(func(domain.Post) domain.PostData); ok {
		r0 = rf(post)
	} else {
		r0 = ret.Get(0).(domain.PostData)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.Post) error); ok {
		r1 = rf(post)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FormatMultiple provides a mock function with given fields: posts
func (_m *PostsRepository) FormatMultiple(posts []domain.Post) ([]domain.PostData, error) {
	ret := _m.Called(posts)

	var r0 []domain.PostData
	if rf, ok := ret.Get(0).(func([]domain.Post) []domain.PostData); ok {
		r0 = rf(posts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PostData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]domain.Post) error); ok {
		r1 = rf(posts)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Get provides a mock function with given fields: meta, resource, status
func (_m *PostsRepository) Get(meta http.Params, resource string, status string) ([]domain.Post, int, error) {
	ret := _m.Called(meta, resource, status)

	var r0 []domain.Post
	if rf, ok := ret.Get(0).(func(http.Params, string, string) []domain.Post); ok {
		r0 = rf(meta, resource, status)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Post)
		}
	}

	var r1 int
	if rf, ok := ret.Get(1).(func(http.Params, string, string) int); ok {
		r1 = rf(meta, resource, status)
	} else {
		r1 = ret.Get(1).(int)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(http.Params, string, string) error); ok {
		r2 = rf(meta, resource, status)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetById provides a mock function with given fields: id
func (_m *PostsRepository) GetById(id int) (domain.Post, error) {
	ret := _m.Called(id)

	var r0 domain.Post
	if rf, ok := ret.Get(0).(func(int) domain.Post); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySlug provides a mock function with given fields: slug
func (_m *PostsRepository) GetBySlug(slug string) (domain.Post, error) {
	ret := _m.Called(slug)

	var r0 domain.Post
	if rf, ok := ret.Get(0).(func(string) domain.Post); ok {
		r0 = rf(slug)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Total provides a mock function with given fields:
func (_m *PostsRepository) Total() (int, error) {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: p
func (_m *PostsRepository) Update(p *domain.PostCreate) (domain.Post, error) {
	ret := _m.Called(p)

	var r0 domain.Post
	if rf, ok := ret.Get(0).(func(*domain.PostCreate) domain.Post); ok {
		r0 = rf(p)
	} else {
		r0 = ret.Get(0).(domain.Post)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.PostCreate) error); ok {
		r1 = rf(p)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
