// Copyright 2020 The Verbis Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// RoleRepository is an autogenerated mock type for the RoleRepository type
type RoleRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: r
func (_m *RoleRepository) Create(r *domain.UserRole) (domain.UserRole, error) {
	ret := _m.Called(r)

	var r0 domain.UserRole
	if rf, ok := ret.Get(0).(func(*domain.UserRole) domain.UserRole); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(domain.UserRole)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.UserRole) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: id
func (_m *RoleRepository) Delete(id int) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(int) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Exists provides a mock function with given fields: name
func (_m *RoleRepository) Exists(name string) bool {
	ret := _m.Called(name)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(name)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Get provides a mock function with given fields:
func (_m *RoleRepository) Get() ([]domain.UserRole, error) {
	ret := _m.Called()

	var r0 []domain.UserRole
	if rf, ok := ret.Get(0).(func() []domain.UserRole); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.UserRole)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetById provides a mock function with given fields: id
func (_m *RoleRepository) GetById(id int) (domain.UserRole, error) {
	ret := _m.Called(id)

	var r0 domain.UserRole
	if rf, ok := ret.Get(0).(func(int) domain.UserRole); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domain.UserRole)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: r
func (_m *RoleRepository) Update(r *domain.UserRole) (domain.UserRole, error) {
	ret := _m.Called(r)

	var r0 domain.UserRole
	if rf, ok := ret.Get(0).(func(*domain.UserRole) domain.UserRole); ok {
		r0 = rf(r)
	} else {
		r0 = ret.Get(0).(domain.UserRole)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*domain.UserRole) error); ok {
		r1 = rf(r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
