// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// SeoMetaRepository is an autogenerated mock type for the SeoMetaRepository type
type SeoMetaRepository struct {
	mock.Mock
}

// UpdateCreate provides a mock function with given fields: id, p
func (_m *SeoMetaRepository) UpdateCreate(id int, p domain.PostOptions) error {
	ret := _m.Called(id, p)

	var r0 error
	if rf, ok := ret.Get(0).(func(int, domain.PostOptions) error); ok {
		r0 = rf(id, p)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
