// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/ainsleyclark/verbis/api/domain"
	mock "github.com/stretchr/testify/mock"
)

// Migrator is an autogenerated mock type for the Migrator type
type Migrator struct {
	mock.Mock
}

// Migrate provides a mock function with given fields: from, to, delete
func (_m *Migrator) Migrate(from domain.StorageChange, to domain.StorageChange, delete bool) (int, error) {
	ret := _m.Called(from, to, delete)

	var r0 int
	if rf, ok := ret.Get(0).(func(domain.StorageChange, domain.StorageChange, bool) int); ok {
		r0 = rf(from, to, delete)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(domain.StorageChange, domain.StorageChange, bool) error); ok {
		r1 = rf(from, to, delete)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
