// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Migrator is an autogenerated mock type for the Migrator type
type Migrator struct {
	mock.Mock
}

// Migrate provides a mock function with given fields: ctx, server, delete
func (_m *Migrator) Migrate(ctx context.Context, server bool, delete bool) (int, error) {
	ret := _m.Called(ctx, server, delete)

	var r0 int
	if rf, ok := ret.Get(0).(func(context.Context, bool, bool) int); ok {
		r0 = rf(ctx, server, delete)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, bool, bool) error); ok {
		r1 = rf(ctx, server, delete)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
