// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	io "io"

	mock "github.com/stretchr/testify/mock"
)

// ZipWriter is an autogenerated mock type for the zipWriter type
type ZipWriter struct {
	mock.Mock
}

// Create provides a mock function with given fields: name
func (_m *ZipWriter) Create(name string) (io.Writer, error) {
	ret := _m.Called(name)

	var r0 io.Writer
	if rf, ok := ret.Get(0).(func(string) io.Writer); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.Writer)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
