// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// CheckSession provides a mock function with given fields: ctx
func (_m *Handler) CheckSession(ctx *gin.Context) {
	_m.Called(ctx)
}

// Login provides a mock function with given fields: ctx
func (_m *Handler) Login(ctx *gin.Context) {
	_m.Called(ctx)
}

// Logout provides a mock function with given fields: ctx
func (_m *Handler) Logout(ctx *gin.Context) {
	_m.Called(ctx)
}

// ResetPassword provides a mock function with given fields: ctx
func (_m *Handler) ResetPassword(ctx *gin.Context) {
	_m.Called(ctx)
}

// SendResetPassword provides a mock function with given fields: ctx
func (_m *Handler) SendResetPassword(ctx *gin.Context) {
	_m.Called(ctx)
}

// VerifyPasswordToken provides a mock function with given fields: ctx
func (_m *Handler) VerifyPasswordToken(ctx *gin.Context) {
	_m.Called(ctx)
}
