// Copyright 2020 The Verbis Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// PublicHandler is an autogenerated mock type for the PublicHandler type
type PublicHandler struct {
	mock.Mock
}

// GetAssets provides a mock function with given fields: g
func (_m *PublicHandler) GetAssets(g *gin.Context) {
	_m.Called(g)
}

// GetUploads provides a mock function with given fields: g
func (_m *PublicHandler) GetUploads(g *gin.Context) {
	_m.Called(g)
}

// Serve provides a mock function with given fields: g
func (_m *PublicHandler) Serve(g *gin.Context) {
	_m.Called(g)
}
