// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	domain "github.com/verbiscms/verbis/api/domain"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Config provides a mock function with given fields:
func (_m *Service) Config() (domain.ThemeConfig, error) {
	ret := _m.Called()

	var r0 domain.ThemeConfig
	if rf, ok := ret.Get(0).(func() domain.ThemeConfig); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.ThemeConfig)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Exists provides a mock function with given fields: _a0
func (_m *Service) Exists(_a0 string) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(string) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Find provides a mock function with given fields: _a0
func (_m *Service) Find(_a0 string) (domain.ThemeConfig, error) {
	ret := _m.Called(_a0)

	var r0 domain.ThemeConfig
	if rf, ok := ret.Get(0).(func(string) domain.ThemeConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.ThemeConfig)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Layouts provides a mock function with given fields:
func (_m *Service) Layouts() (domain.Layouts, error) {
	ret := _m.Called()

	var r0 domain.Layouts
	if rf, ok := ret.Get(0).(func() domain.Layouts); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Layouts)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields:
func (_m *Service) List() ([]domain.ThemeConfig, error) {
	ret := _m.Called()

	var r0 []domain.ThemeConfig
	if rf, ok := ret.Get(0).(func() []domain.ThemeConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.ThemeConfig)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Screenshot provides a mock function with given fields: _a0, file
func (_m *Service) Screenshot(_a0 string, file string) ([]byte, domain.Mime, error) {
	ret := _m.Called(_a0, file)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(string, string) []byte); ok {
		r0 = rf(_a0, file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	var r1 domain.Mime
	if rf, ok := ret.Get(1).(func(string, string) domain.Mime); ok {
		r1 = rf(_a0, file)
	} else {
		r1 = ret.Get(1).(domain.Mime)
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(string, string) error); ok {
		r2 = rf(_a0, file)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Set provides a mock function with given fields: _a0
func (_m *Service) Set(_a0 string) (domain.ThemeConfig, error) {
	ret := _m.Called(_a0)

	var r0 domain.ThemeConfig
	if rf, ok := ret.Get(0).(func(string) domain.ThemeConfig); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(domain.ThemeConfig)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Templates provides a mock function with given fields:
func (_m *Service) Templates() (domain.Templates, error) {
	ret := _m.Called()

	var r0 domain.Templates
	if rf, ok := ret.Get(0).(func() domain.Templates); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(domain.Templates)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
