// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AuthHandler is an autogenerated mock type for the AuthHandler type
type AuthHandler struct {
	mock.Mock
}

// Login provides a mock function with given fields: g
func (_m *AuthHandler) Login(g *gin.Context) {
	_m.Called(g)
}

// Logout provides a mock function with given fields: g
func (_m *AuthHandler) Logout(g *gin.Context) {
	_m.Called(g)
}

// ResetPassword provides a mock function with given fields: g
func (_m *AuthHandler) ResetPassword(g *gin.Context) {
	_m.Called(g)
}

// SendResetPassword provides a mock function with given fields: g
func (_m *AuthHandler) SendResetPassword(g *gin.Context) {
	_m.Called(g)
}

// VerifyEmail provides a mock function with given fields: g
func (_m *AuthHandler) VerifyEmail(g *gin.Context) {
	_m.Called(g)
}

// VerifyPasswordToken provides a mock function with given fields: g
func (_m *AuthHandler) VerifyPasswordToken(g *gin.Context) {
	_m.Called(g)
}
