// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// CategoryHandler is an autogenerated mock type for the CategoryHandler type
type CategoryHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: g
func (_m *CategoryHandler) Create(g *gin.Context) {
	_m.Called(g)
}

// Delete provides a mock function with given fields: g
func (_m *CategoryHandler) Delete(g *gin.Context) {
	_m.Called(g)
}

// Get provides a mock function with given fields: g
func (_m *CategoryHandler) Get(g *gin.Context) {
	_m.Called(g)
}

// GetById provides a mock function with given fields: g
func (_m *CategoryHandler) GetById(g *gin.Context) {
	_m.Called(g)
}

// Update provides a mock function with given fields: g
func (_m *CategoryHandler) Update(g *gin.Context) {
	_m.Called(g)
}
