// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// FrontendHandler is an autogenerated mock type for the FrontendHandler type
type FrontendHandler struct {
	mock.Mock
}

// GetUploads provides a mock function with given fields: g
func (_m *FrontendHandler) GetUploads(g *gin.Context) {
	_m.Called(g)
}

// Serve provides a mock function with given fields: g
func (_m *FrontendHandler) Serve(g *gin.Context) {
	_m.Called(g)
}
