// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// OptionsHandler is an autogenerated mock type for the OptionsHandler type
type OptionsHandler struct {
	mock.Mock
}

// Get provides a mock function with given fields: g
func (_m *OptionsHandler) Get(g *gin.Context) {
	_m.Called(g)
}

// GetByName provides a mock function with given fields: g
func (_m *OptionsHandler) GetByName(g *gin.Context) {
	_m.Called(g)
}

// UpdateCreate provides a mock function with given fields: g
func (_m *OptionsHandler) UpdateCreate(g *gin.Context) {
	_m.Called(g)
}
