// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// SpaHandler is an autogenerated mock type for the SpaHandler type
type SpaHandler struct {
	mock.Mock
}

// Serve provides a mock function with given fields: g
func (_m *SpaHandler) Serve(g *gin.Context) {
	_m.Called(g)
}
