// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Tester is an autogenerated mock type for the tester type
type Tester struct {
	mock.Mock
}

// get provides a mock function with given fields:
func (_m *Tester) get() {
	_m.Called()
}
