// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"

	recovery "github.com/ainsleyclark/verbis/api/recovery"
)

// Recovery is an autogenerated mock type for the Recovery type
type Recovery struct {
	mock.Mock
}

// HttpRecovery provides a mock function with given fields:
func (_m *Recovery) HttpRecovery() gin.HandlerFunc {
	ret := _m.Called()

	var r0 gin.HandlerFunc
	if rf, ok := ret.Get(0).(func() gin.HandlerFunc); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(gin.HandlerFunc)
		}
	}

	return r0
}

// Recover provides a mock function with given fields: cfg
func (_m *Recovery) Recover(cfg recovery.Config) []byte {
	ret := _m.Called(cfg)

	var r0 []byte
	if rf, ok := ret.Get(0).(func(recovery.Config) []byte); ok {
		r0 = rf(cfg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}
