// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	recovery "github.com/verbiscms/verbis/api/recovery"
)

// TplData is an autogenerated mock type for the TplData type
type TplData struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *TplData) Execute() *recovery.Data {
	ret := _m.Called()

	var r0 *recovery.Data
	if rf, ok := ret.Get(0).(func() *recovery.Data); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*recovery.Data)
		}
	}

	return r0
}
