// Code generated by mockery 2.7.5. DO NOT EDIT.

package mocks

import (
	trace "github.com/ainsleyclark/verbis/api/recovery/trace"
	mock "github.com/stretchr/testify/mock"
)

// Tracer is an autogenerated mock type for the Tracer type
type Tracer struct {
	mock.Mock
}

// Trace provides a mock function with given fields: depth, skip
func (_m *Tracer) Trace(depth int, skip int) trace.Stack {
	ret := _m.Called(depth, skip)

	var r0 trace.Stack
	if rf, ok := ret.Get(0).(func(int, int) trace.Stack); ok {
		r0 = rf(depth, skip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(trace.Stack)
		}
	}

	return r0
}
