// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Delete provides a mock function with given fields: g
func (_m *Handler) Delete(g *gin.Context) {
	_m.Called(g)
}

// Find provides a mock function with given fields: g
func (_m *Handler) Find(g *gin.Context) {
	_m.Called(g)
}

// List provides a mock function with given fields: g
func (_m *Handler) List(g *gin.Context) {
	_m.Called(g)
}

// Update provides a mock function with given fields: g
func (_m *Handler) Update(g *gin.Context) {
	_m.Called(g)
}

// Upload provides a mock function with given fields: g
func (_m *Handler) Upload(g *gin.Context) {
	_m.Called(g)
}
