// Code generated by mockery 2.7.4. DO NOT EDIT.

package mocks

import (
	mail "github.com/ainsleyclark/go-mail"

	mock "github.com/stretchr/testify/mock"
)

// Mailer is an autogenerated mock type for the Mailer type
type Mailer struct {
	mock.Mock
}

// Send provides a mock function with given fields: t
func (_m *Mailer) Send(t *mail.Transmission) {
	_m.Called(t)
}
